### ISSUE TITLE
Shadows rendering white instead of black

### ISSUE THREAD

**Issue by ItsRogueRen** [ExpiredPopsicle/SnekStudio#25]
## System Info
OS: Linux (Nobara 40, Fedora based)
GPU: AMD RX 7700XT
CPU: Ryzen 9 5900X
GPU Drivers: Mesa 24.3.0-devel
WM: Kwin (Wayland)

## Issue
Not 100% certain what Vroid version my model is as it has been heavily modified throughout the years, but I'm pretty sure it's 0.0 and not 1.x

Model loads in just fine, but shadows are rendered as white instead of black. My model has been modified in Blender but it was originally created in Vroid Studio. 

![image](https://github.com/user-attachments/assets/1b9df90d-a827-4504-9fcd-17e50fa6e2b0)

 All settings menus are blank except for the window options, so I assume settings aren't finished yet. If they are there and I just don't see them, I can test settings more to see if I can make the issue go away.

**Comment by ExpiredPopsicle** [comment]
So a few things here:

Most likely, it's just that the lighting for the scene defaults to a pretty bright ambient light energy, which will fill in a lot of those shadows. In the "Mods" window, check the "Scene_Basic" settings and you can adjust the light energy and direction.

Second, check the "shade texture" input on your model in Blender. The VRM addon for Blender doesn't have great English documentation, but as far as I can tell that's intended to be the color of the material in shadow. (I ran into this in the past with my own model because the VRM addon picks some really bright color for the shade color by default for the MToon_unversioned node.)

![image](https://github.com/user-attachments/assets/b305a765-237c-4727-8746-80de523cee26)

Some of the windows here used to have settings that got split off into individual modules.
- The "scene" settings window used to have all the lighting settings, which got moved into the Scene_Basic module.
- The "general" settings window used to have all the VMC/MediaPipe options until those both got split off into individual models.

So these windows are actually deprecated. They're still there just in case something else needs to go back into them, but they may just be removed entirely in a future version.

Anyway, let me know if any of these help. If so, the real bug may just be that the UI isn't clear about where to find the settings. In that case I'll close this and make a new UI improvement issue.

**Comment by ExpiredPopsicle** [comment]
I'm going to go ahead and close this for now, because I suspect it was related to those two things I mentioned. Let me know if those aren't related and I can re-open the issue.
