### ISSUE TITLE
Move settings and Python cache to live next to the executable

### ISSUE THREAD

**Issue by ExpiredPopsicle** [ExpiredPopsicle/SnekStudio#64]
Having to dig into the user settings directory every time I want to mess with the config files directly is getting tiresome, and there's too much potential for cruft to be left around after program removal.

For development mode, make use of a .gdignore directory inside the project tree.

**Comment by copygirl** [comment]
It would be nice if this was toggle-able.

It'd make more sense to have them in per-user folder(s) for system-wide installations.

**Comment by ExpiredPopsicle** [comment]
Behavior updated in 5eb487f .

**Comment by alexbobp** [comment]
This seems like it would be useful for many users if it were optional (after all, many applications have a "portable" version)...  but it doesn't seem like a good idea for this to be the only option.  Being able to separate software/executables from configuration data can be important in many situations...  the most obvious one being (as copygirl mentioned) a global installation package to be shared between users.  This separation also simplifies the update process in general (as a user can delete the old install and unpack a fresh copy, without worrying about rooting out their config information).

My suggestion for how to handle this would be to accept environment variables to specify paths for configuration, cache, and extra mods, or alternately, have a config file that can specify such paths.  Snek Studio could default to operating like a "portable" app if neither of these are specified, but this would allow for distribution packages that allow non-root users to configure their Snek Studio instance as well as install mods.  A distro packaged version of Snek Studio would likely want to specify configuration/cache/mods paths in the user's home directory, and it would create less burden on such distro package maintainers if they can simply use a launcher script or config file to do so, rather than having to patch and repack the gdscript source code.
