### ISSUE TITLE
Sometimes fingers bend backwards

### ISSUE THREAD

**Issue by ExpiredPopsicle** [ExpiredPopsicle/SnekStudio#8]
Rest position is fingers in a painful-looking bent-up position.

I don't currently have a model that can repro this, unfortunately.

**Comment by exodrifter** [comment]
I have a model that reproduces this! 

Here's my model in Snek Studio:

https://github.com/user-attachments/assets/43d76a00-4ee4-4e72-98e6-2c34a3677f59

And here it is in Warudo (recorded by the artist who made my model, since I'm on Linux):

https://github.com/user-attachments/assets/0373f240-cbf8-4550-884a-c9a78406af95

i talked to the artist of my model about this issue and they mentioned that my model doesn't have all 3 bones for each finger and that it only has 2, so that might be a factor for why this issue happens.

**Comment by the-furry-hubofeverything** [comment]
when I get the time, I'll see if I can reproduce this with a basic hand model

**Comment by ExpiredPopsicle** [comment]
Appreciate it, but I was given access to another model that reproduces the issue (for likely the same reason).

I'm also midway through a refactor of the finger tracking code right now that should solve the issue.

**Comment by ExpiredPopsicle** [comment]
Fix for this is (finally) incoming, but I have some code cleanup to do. It's part of a larger refactor.

**Comment by ExpiredPopsicle** [comment]
This should be fixed now. Let me know if you're still having any issues with it.
